make pulse the default protocol
But it doesn't work out so well:

<terminal>
root@barley:~# date; ~ross/src/ucsf-vpn/bin/ucsf-vpn --verbose --debug start; date
Tue 28 Jun 2022 02:00:39 PM PDT
DEBUG: Next CLI argument: start
DEBUG: Method: openconnect
DEBUG: Will authenticate via push (approve and confirm in Duo app)
DEBUG: call: /home/ross/src/ucsf-vpn/bin/ucsf-vpn --verbose --debug start
DEBUG: action: start
DEBUG: VPN server: remote.ucsf.edu
DEBUG: Realm: 'Dual-Factor Pulse Clients'
DEBUG: protocol: pulse
DEBUG: user:
DEBUG: pwd=<missing>
DEBUG: token=push
DEBUG: verbose: true
DEBUG: force: false
DEBUG: validate: pid,ipinfo
DEBUG: dryrun: false
DEBUG: extras:
DEBUG: method: openconnect
DEBUG: gui: true
DEBUG: speed: 1.0
DEBUG: netrc_machines: remote.ucsf.edu
DEBUG: pid_file: /root/.config/ucsf-vpn/openconnect.pid
DEBUG: PID file does not exists: /root/.config/ucsf-vpn/openconnect.pid
DEBUG: openconnect_pid: -1
DEBUG: pii_file: /root/.config/ucsf-vpn/tmp.3q15W2xKuc-ipinfo.json
DEBUG: openconnect_start() ...
DEBUG: PID file does not exists: /root/.config/ucsf-vpn/openconnect.pid
DEBUG: PID file does not exists: /root/.config/ucsf-vpn/openconnect.pid
DEBUG: is_connected()
DEBUG: connection_details()
DEBUG: Ping servers: [n=7]: 9.9.9.9
DEBUG: Ping server: '9.9.9.9'
INFO: Pinging '9.9.9.9' once
INFO: Verified that internet connection works
INFO: Getting public IP (from https://ipinfo.io/ip)
DEBUG: Calling: curl --silent https://ipinfo.io/json > "/root/.config/ucsf-vpn/tmp.3q15W2xKuc-ipinfo.json"
DEBUG: Public connection information: { "ip": "66.181.128.6", "hostname": "m128-6.dsl.rawbw.com", "city": "San Francisco", "region": "California", "country": "US", "loc": "37.7354,-122.4571", "org": "AS7961 Raw Bandwidth Communications, Inc.", "postal": "94127", "timezone": "America/Los_Angeles", "readme": "https://ipinfo.io/missingauth"}
DEBUG: Ping servers: [n=7]: 9.9.9.9
DEBUG: Ping server: '9.9.9.9'
INFO: Pinging '9.9.9.9' once
INFO: Preparing to connect to VPN server 'remote.ucsf.edu'
DEBUG: 'sudo' is already active
INFO: Administrative ("sudo") rights already establish
DEBUG: Detected .netrc file: /home/ross/.netrc
DEBUG: - search: remote.ucsf.edu
DEBUG: - search pattern: ^[ \t]*machine[ \t]+remote.ucsf.edu([ \t]+|$)
DEBUG: - found: remote.ucsf.edu
DEBUG: - user=rdboylan
DEBUG: - pwd=<hidden>
DEBUG: call: /home/ross/src/ucsf-vpn/bin/ucsf-vpn --verbose --debug start
DEBUG: user: rdboylan
DEBUG: pwd: <hidden>
DEBUG: token: push
DEBUG: opts:  --protocol=pulse https://remote.ucsf.edu/pulse --background --user=rdboylan --passwd-on-stdin --pid-file=/root/.config/ucsf-vpn/openconnect.pid
DEBUG: call: sudo openconnect  --protocol=pulse https://remote.ucsf.edu/pulse --background --user=rdboylan --passwd-on-stdin --pid-file=/root/.config/ucsf-vpn/openconnect.pid --authgroup="Dual-Factor Pulse Clients"
NOTE: Open the Duo Mobile app on your smartphone or tablet to confirm ...
INFO: Connecting to VPN server 'remote.ucsf.edu'
Connected to 64.54.201.78:443
SSL negotiation with remote.ucsf.edu
Connected to HTTPS on remote.ucsf.edu with ciphersuite (TLS1.2)-(RSA)-(AES-128-GCM)
Got HTTP response: HTTP/1.1 101 Switching Protocols
Unexpected IF-T/TLS packet when expecting configuration.
DEBUG: Removing file: /root/.config/ucsf-vpn/tmp.3q15W2xKuc-ipinfo.json
DEBUG: OpenConnect standard error:
DEBUG: Enter user credentials:
Enter secondary credentials:
Secondary password:
Invalid ESP setup
Insufficient configuration found
Creating SSL connection failed
DEBUG: PID file does not exists: /root/.config/ucsf-vpn/openconnect.pid
DEBUG: pid=-1
Enter user credentials:
Enter secondary credentials:
Secondary password:
Invalid ESP setup
Insufficient configuration found
Creating SSL connection failed
DEBUG: Ping servers: [n=15]: remote.ucsf.edu
DEBUG: Ping server: 'remote.ucsf.edu'
INFO: Pinging 'remote.ucsf.edu' once
ERROR: Failed to connect to VPN server. Likely reason: Check your username, password, and token. You can test your credentials via the Web VPN at https://remote-vpn01.ucsf.edu/. Miscellaneous: The VPN server (remote.ucsf.edu) responds to ping [ucsf-vpn 5.4.0, OpenConnect 8.10-2+b1]
DEBUG: Exiting with exit code 1
Tue 28 Jun 2022 02:01:02 PM PDT
root@barley:~# date; ~ross/src/ucsf-vpn/bin/ucsf-vpn status
Tue 28 Jun 2022 02:03:36 PM PDT
OpenConnect status: No 'openconnect' process running
Public IP information: ip=66.181.128.6, hostname=m128-6.dsl.rawbw.com, org=AS7961 Raw Bandwidth Communications, Inc.
Not connected to the VPN
</terminal>

This perhaps the rekeying bug referenced in
https://github.com/HenrikBengtsson/ucsf-vpn/issues/45, which refers to
https://www.infradead.org/openconnect/changelog.html post 8.10 bug
fixes.